config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "destinations#index"
  devise_for :users
  resources :destinations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :destinations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  def index
    @destinations = current_user.destinations
  end

  def show
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = current_user.destinations.new(destination_params)
    if @destination.save
      flash[:success] = "New Destination Created"
      redirect_to destinations_path
    else
      flash[:error] = "Error #{@destination.errors.full_messages.join('\n')}"
      render :new
    end
  end

  def update
    if @destination.update(destination_params)
      redirect_to destinations_path
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @destination.destroy
    redirect_to destinations_path
  end


  private

  def set_destination
    @destination = current_user.destinations.find(params[:id])
  end

  def destination_params
    params.require(:destination).permit(:name, :location)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/edit.html.erb
<h2>Edit Climbing Destination</h2>

<%= form_with(model: @destination, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, required: true, placeholder: "Location" %>
  </div>
  <%= f.submit 'Update' %>
<% end %>

app/views/destinations/index.html.erb
<h2>Your Climbing Destinations</h2>
<h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
<hr />
<%= link_to "Plan Your Next Trip", new_destination_path %>
<ul>
<% @destinations.each do |destination| %>
  <li><%= destination.name %> - <%= destination.location %></li>
  <%= link_to "Edit Destination", edit_destination_path(destination) %>
<% end %>
</ul>

<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

app/views/destinations/new.html.erb
<h2>Add a New Destination!</h2>

<%= form_with(model: @destination, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, required: true, placeholder: "Location" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/destinations/show.html.erb
<h1>Destinations#show</h1>
<p>Find me in app/views/destinations/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">
      <%= link_to 'Home', root_path  %>
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
          <%= link_to "Destinations",  destinations_path %>
        </li>
        <li>
          <%= link_to "logout",  destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'sign up',new_user_registration_path%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimberProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>